name: unfold-step2svg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pythonocc-core=7.9.0
  - numpy
  - lxml
  - shapely
  - ifcopenshell=0.8.0
  - pip
  - pip:
      - fastapi==0.116.1
      - uvicorn==0.35.0
      - python-multipart==0.0.20
      - pydantic==2.11.7
      - svgwrite==1.4.3
      - scipy==1.15.3